version: '3'

services:
  database:
    image: 'mysql:latest'
    ports:
    - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
      MYSQL_DATABASE: 'todo_app'
      MYSQL_USER: 'root'
    volumes:
    - 'app_data:/var/lib/mysql'
    command:
    - 'mysqld'
    - '--character-set-server=utf8mb4'
    - '--collation-server=utf8mb4_unicode_ci'
    - '--default-authentication-plugin=mysql_native_password'

volumes:
  app_data: ~
